-- YardLine seed — generated by scripts/seed-yards.ts
-- generated_at: 2026-08-02T01:38:48.197Z
-- records: 12  with_phone: 11 (92%)
-- Every row traces to a source_url. No value here was invented.

insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Richard Kerns Truck Parts', '2495 Forest Pkwy', 'Ellenwood', 'GA', '30294', null, 33.6116689, -84.3091543, '404-366-4843', 'https://richardkernstruckparts.com/', 'verified_web', 'https://richardkernstruckparts.com/', null, 'hd_salvage', null, true, 'richard kerns truck parts|3664843')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Crest Truck Parts', '640 J.F.H. Pkwy', 'Cartersville', 'GA', '30120', 'Bartow', 34.1597749, -84.7884408, '770-382-1595', 'https://cresttruckparts.com/', 'verified_web+heavytruckparts.net', 'https://cresttruckparts.com/ | https://www.heavytruckparts.net/vendors.php | https://www.heavytruckparts.net/search.php?fltpc=2251343&store=1', null, 'hd_salvage', 12070, true, 'crest truck parts|3821595')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('HD Truck Repair & Service', '136 Truck Stop Way', 'Jackson', 'GA', '30233', null, null, null, '770-775-4739', 'https://hdtrs.com/', 'verified_web+heavytruckparts.net', 'https://hdtrs.com/ | https://www.heavytruckparts.net/vendors.php | https://www.heavytruckparts.net/search.php?fltpc=5299744&store=1', null, 'hd_salvage', 1645, true, 'hd truck repair service|7754739')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('AFS Diesel Truck & Body', '3939 Moreland Avenue', 'Conley', 'GA', '30288', null, 33.6477207, -84.3293976, '404-596-4395', 'https://www.associatedfuelsystems.com/', 'verified_web', 'https://www.associatedfuelsystems.com/parts-department-services', null, 'hd_salvage', null, null, 'afs diesel truck body|5964395')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Simpson & Simpson LLC', '4290 Holly Springs Road', 'Gillsville', 'GA', '30543', null, null, null, '770-532-4013', 'https://www.simpsonsusedtruckparts.com/', 'verified_web', 'https://www.simpsonsusedtruckparts.com/used-commercial-truck-parts', null, 'hd_salvage', null, null, 'simpson simpson|5324013')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Rush Truck Centers – Smyrna', '2120 Atlanta Road Southeast', 'Smyrna', 'GA', '30080', 'Cobb', 33.9014405, -84.5249946, '678-718-3000', 'https://www.rushtruckcenters.com/locations/19010000-smyrna', 'osm', 'https://www.openstreetmap.org/way/264974900', 'way/264974900', 'oem_dealer', null, null, 'rush truck centers smyrna|7183000')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Peterbilt of Atlanta', '2395 Old US 41 Highway Northwest', null, 'GA', null, null, 34.0109448, -84.6074383, '404-592-9980', 'https://peteatlanta.com/', 'osm', 'https://www.openstreetmap.org/way/283272835', 'way/283272835', 'oem_dealer', null, null, 'peterbilt atlanta|5929980')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Rush Truck Centers – Doraville', '2500 Button Gwinnett Drive', 'Atlanta', 'GA', '30340', 'Fulton', 33.9206105, -84.2412512, '678-578-1600', 'https://www.rushtruckcenters.com/locations/19040000-doraville', 'osm', 'https://www.openstreetmap.org/way/388292690', 'way/388292690', 'oem_dealer', null, null, 'rush truck centers doraville|5781600')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Nextran Truck Centers', '1414 Shiloh Road Northwest', null, 'GA', null, null, 34.0512635, -84.592738, null, 'https://nextranusa.com/locations/kennesaw/', 'osm', 'https://www.openstreetmap.org/way/793655457', 'way/793655457', 'oem_dealer', null, null, 'nextran truck centers|')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Rush Truck Centers – Gainesville', '2045 Atlas Circle', 'Gainesville', 'GA', '30501', null, 34.280499, -83.848595, '470-248-7050', 'https://www.rushtruckcenters.com/locations/19070000-gainesville', 'osm', 'https://www.openstreetmap.org/way/1057897868', 'way/1057897868', 'oem_dealer', null, null, 'rush truck centers gainesville|2487050')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('Forest Park Tractor & Trailer', '5244 Springdale Road', 'Forest Park', 'GA', '30297', 'Clayton', 33.6153386, -84.3732459, '404-361-8785', null, 'heavytruckparts.net', 'https://www.heavytruckparts.net/vendors.php | https://www.heavytruckparts.net/search.php?fltpc=781247&store=1', null, 'hd_salvage', 58, true, 'forest park tractor trailer|3618785')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
insert into yards (name, address, city, state, zip, county, lat, lng, phone, website, source, source_url, osm_id, yard_type, published_listing_count, publishes_online, dedupe_key) values ('LKQ Evans Heavy Truck Parts', '1510 Highway 29 N', 'Athens', 'GA', '30601', null, null, null, '855-557-8782', null, 'heavytruckparts.net', 'https://www.heavytruckparts.net/vendors.php | https://www.heavytruckparts.net/search.php?fltpc=254076&store=24', null, 'hd_salvage', 39853, true, 'lkq evans heavy truck parts|5578782')
on conflict (dedupe_key) do update set
  phone = coalesce(yards.phone, excluded.phone),
  address = coalesce(yards.address, excluded.address),
  city = coalesce(yards.city, excluded.city),
  zip = coalesce(yards.zip, excluded.zip),
  county = coalesce(yards.county, excluded.county),
  lat = coalesce(yards.lat, excluded.lat),
  lng = coalesce(yards.lng, excluded.lng),
  website = coalesce(yards.website, excluded.website),
  published_listing_count = coalesce(yards.published_listing_count, excluded.published_listing_count),
  publishes_online = coalesce(yards.publishes_online, excluded.publishes_online),
  source_url = excluded.source_url,
  updated_at = now();
